channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::cnvkit=0.9.10
  # renovate: datasource=conda depName=bioconda/htslib
  - bioconda::htslib=1.17
  # renovate: datasource=conda depName=bioconda/samtools
  - bioconda::samtools=1.17

# pipelines:
#  - sarek
