# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "abundance_differential_filter"
description: Perform differential analysis and filtering on abundance data
keywords:
  - differential expression
  - RNA-seq
  - DESeq2
  - limma
  - filtering
components:
  - deseq2/differential
  - limma/differential
  - custom/filterdifferentialtable
input:
  - ch_input:
      type: tuple
      description: |
        Channel with input data for differential analysis
        Structure: [ val(meta_input), path(counts), val(analysis_method) ]
  - ch_samplesheet:
      type: tuple
      description: |
        Channel with sample information
        Structure: [ val(meta_exp), path(samplesheet) ]
  - ch_transcript_lengths:
      type: tuple
      description: |
        Channel with transcript length information
        Structure: [ val(meta_exp), path(transcript_lengths) ]
  - ch_control_features:
      type: tuple
      description: |
        Channel with control features information
        Structure: [ val(meta_exp), path(control_features) ]
  - ch_contrasts:
      type: tuple
      description: |
        Channel with contrast information
        Structure: [ val(meta_contrast), val(contrast_variable), val(reference), val(target) ]
  - FC_threshold:
      type: float
      description: |
        Fold change threshold for filtering differential results
  - padj_threshold:
      type: float
      description: |
        Adjusted p-value threshold for filtering differential results

output:
  - results_genewise:
      type: file
      description: Unfiltered differential analysis results
      pattern: "*.{csv,tsv}"
  - results_genewise_filtered:
      type: file
      description: Filtered differential analysis results
      pattern: "*.{csv,tsv}"
  - normalised_matrix:
      type: file
      description: Normalised count matrix
      pattern: "*.{csv,tsv}"
  - variance_stabilised_matrix:
      type: file
      description: Variance stabilised count matrix (DESeq2 only)
      pattern: "*.{csv,tsv}"
  - model:
      type: file
      description: Statistical model object from differential analysis
      pattern: "*.rds"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@pinin4fjords"
maintainers:
  - "@pinin4fjords"
